repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: ['--max-line-length', '120', '--extend-ignore', 'E203']

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      args: ['-l', '120', '-t', 'py311']

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --ignore-init-module-imports
          - --in-place
          - --recursive

  - repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort
        args: ['--profile', 'black', '--filter-files', 'true']

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ['--skip', 'B101,B110']

default_language_version:
  python: python3.11
